---
mariadb_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql

mariadb_root_password: "changeme"

mariadb_bind_address: "127.0.0.1"
mariadb_port: 3306

# Nouvel utilisateur à créer avec tous privilèges
mariadb_user_name: ""
mariadb_user_password: ""
