---
# Rôle : user
# Objectif : gérer un ou plusieurs utilisateurs

- name: Créer l'utilisateur principal
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: present
    shell: /bin/bash
  when: user_name is defined
