---
- name: Vérifier que le nom du service est renseigné
  fail:
    msg: "La variable 'service_name' doit être renseignée."
  when: service_name == ""

- name: Gérer le service système avec le module service
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  become: yes
