---
- name: Vérifier qu'il y a au moins un élément à copier
  ansible.builtin.debug:
    msg: "Aucun fichier à copier (copy_dynamic_items est vide)"
  when: copy_dynamic_items | length == 0

- name: Copier les fichiers dynamiquement
  ansible.builtin.include_tasks: copy_one.yml
  loop: "{{ copy_dynamic_items }}"
  loop_control:
    loop_var: copy_item
  when: copy_dynamic_items | length > 0