---
# URL du dépôt Git à cloner (obligatoire)
git_repo_url: ""

# Branche, tag ou commit à utiliser (défaut: master)
git_version: "master"

# Chemin absolu où cloner le dépôt (obligatoire)
git_dest: ""

# Paramètre pour forcer la mise à jour même si le dépôt existe (booléen, défaut true)
git_force: true

# Propriétaire du répertoire cloné (optionnel)
git_owner: "root"

# Groupe du répertoire cloné (optionnel)
git_group: "root"

# Mode d'accès au dépôt Git : 'clone' ou 'pull' (optionnel, par défaut clone)
# (si vous souhaitez traiter différemment, sinon ignorez)
git_update_method: "clone"
