---
# Chemin complet de la cible à gérer (fichier, répertoire ou lien)
file_path: ""

# État désiré de la cible : 'file', 'directory', 'link', 'absent'
file_state: "directory"

# Propriétaire (string, optionnel)
file_owner: "root"

# Groupe (string, optionnel)
file_group: "root"

# Permissions (string, mode numérique, ex: '0755', optionnel)
file_mode: "0755"

# Chemin cible si état 'link' (obligatoire si file_state = 'link')
file_src: ""

# Option pour suivre le lien symbolique ou non
file_follow: false
