---
# Liste des paquets firewalld à installer
firewalld_packages:
  - firewalld

# Liste des ports à autoriser dans le firewall (exemple "80/tcp")
firewalld_ports: []

# Liste des services firewalld à autoriser (exemple : "http", "ssh")
firewalld_services: []

# Zone firewalld par défaut dans laquelle ajouter règles (exemple "public")
firewalld_zone: "public"

# Si true, active et démarre firewalld (true recommandé)
firewalld_enabled: true
