---
# Variables par défaut pour le rôle. Adaptables lors de l'appel du rôle.

web_domain: "localhost"
web_port: 80
web_admin_email: "webmaster@localhost"
web_doc_root: "/var/www/html"

php_packages:
  - php
  - php-cli
  - libapache2-mod-php
  - php-common

mariadb_packages:
  - mariadb-server
  - php-mysql

postgres_packages:
  - postgresql
  - php-pgsql

oracle_packages:
  - php-pear
  - php-dev
  - php-oci8

mysql_packages:
  - mysql-server
  - php-mysql

use_mariadb: false
use_postgres: false
use_oracle: false
use_mysql: false
