---
# Chemin local ou distant vers le fichier archive à extraire (obligatoire)
unarchive_src: ""

# Chemin absolu du répertoire destination de l’extraction (obligatoire)
unarchive_dest: ""

# Indique si l’archive doit être décompressée même si les fichiers existent déjà
unarchive_remote_src: false

# Propriétaire du contenu extrait (optionnel)
unarchive_owner: "root"

# Groupe du contenu extrait (optionnel)
unarchive_group: "root"

# Permissions pour les répertoires créés (optionnel, ex: "0755")
unarchive_mode: "0755"

# Supprimer le fichier archive après extraction (booléen)
unarchive_delete_after: false
