---
# Packages Python 3 suivant la famille d’OS
python3_packages_debian:
  - python3
  - python3-pip
  - python3-venv

python3_packages_redhat:
  - python3
  - python3-pip
  - python3-virtualenv

# Mettre à jour le cache des paquets avant installation (booléen)
python3_update_cache: true
