---
# Type de monitoring à installer ('prometheus' ou 'node_exporter' seulement)
monitoring_type: "prometheus"

# Version Prometheus à installer
prometheus_version: "2.45.0"

# Configuration Prometheus (cibles à monitorer)
prometheus_targets:
  - targets: ['localhost:9100']
    labels:
      job: node

# Port d'écoute Prometheus
prometheus_port: 9090

# Utilisateur système pour Prometheus
prometheus_user: "prometheus"

# Activer les services de monitoring
monitoring_services_enabled: true
