---
# Liste des paquets à gérer (installation, mise à jour ou suppression)
package_list: []

# Etat désiré des paquets : 'present', 'latest' ou 'absent'
package_state: present

# Mise à jour du cache avant action (booléen)
package_update_cache: true
