---
# Variables par défaut pour le rôle apache2_php_mariaDB_role

# Apache
apache2_php_mariadb_listen_port: 80
apache2_php_mariadb_server_name: "www.example.local"
apache2_php_mariadb_document_root: "/var/www/php_app"

# PHP
apache2_php_mariadb_php_packages:
  - php
  - libapache2-mod-php
  - php-mysql

# MariaDB
apache2_php_mariadb_install_server: true      # true = installe le serveur MariaDB, false = seulement client
apache2_php_mariadb_packages:
  - mariadb-server
  - mariadb-client

apache2_php_mariadb_db_name: "appdb"
apache2_php_mariadb_db_user: "appuser"
apache2_php_mariadb_db_password: "changeme"

# Fichier index.php déployé par défaut (dynamique)
apache2_php_mariadb_deploy_example_app: true