---
# Activer ou non la gestion de la synchro horaire
timesync_role_manage: true

# Backend de synchronisation à utiliser :
# - "timesyncd" : systemd-timesyncd
# - "chrony"    : chronyd/chrony
# - "ntp"       : ancien serveur ntp
# Si vide -> on choisit automatiquement (par exemple "timesyncd" sur Debian récents)
timesync_role_backend: ""

# Liste des serveurs NTP (quel que soit le backend)
timesync_role_ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"

# Configuration spécifique pour chrony (optionnelle)
timesync_role_chrony_package: "chrony"
timesync_role_chrony_service: "chronyd"
timesync_role_chrony_conf_file: "/etc/chrony/chrony.conf"

# Configuration spécifique pour systemd-timesyncd (Debian/Ubuntu)
timesync_role_timesyncd_conf_file: "/etc/systemd/timesyncd.conf"
timesync_role_timesyncd_service: "systemd-timesyncd"

# Configuration spécifique pour ntp (ancien, optionnel)
timesync_role_ntp_package: "ntp"
timesync_role_ntp_service: "ntp"
timesync_role_ntp_conf_file: "/etc/ntp.conf"

# Est-ce qu'on active et démarre le service ?
timesync_role_enable_service: true
timesync_role_ensure_running: true