---
redis_port: 6379
redis_bind: "127.0.0.1"
redis_requirepass: ""
redis_maxmemory: "256mb"

redis_config:
  appendonly: "yes"
  appendfilename: "appendonly.aof"
  save: ["900 1", "300 10", "60 10000"]

redis_enabled: true
redis_version: "latest"
