---
# Nom de l’utilisateur à créer/gérer (obligatoire)
user_name: ""

# UID (optionnel)
user_uid: null

# Groupe principal (optionnel)
user_group: ""

# Groupes supplémentaires (liste optionnelle)
user_groups: []

# Shell de l’utilisateur (par défaut /bin/bash)
user_shell: "/bin/bash"

# Home directory (automatique par défaut, peut être précisé)
user_home: ""

# Mot de passe chiffré (hash Linux) (optionnel, ne pas mettre en clair)
user_password: ""

# Créer le répertoire home si absent (booléen)
user_create_home: true

# Supprimer l’utilisateur si true, sinon crée/modifie (booléen)
user_state: present
