---
# Activer ou non la gestion des mises à jour système
sys_upgrade_role_manage: true

# Mettre à jour le cache des paquets (apt/yum/dnf/zypper) ?
sys_upgrade_role_update_cache: true

# Type de mise à jour (principalement pour apt) :
# - "none"      : pas de mise à jour des paquets (seulement update_cache éventuel)
# - "safe"      : équivalent à 'apt upgrade' (mise à jour sans supprimer)
# - "full"      : équivalent à 'apt full-upgrade' / 'dist-upgrade'
sys_upgrade_role_upgrade_type: "safe"

# Sur RedHat/CentOS :
# - si true -> 'yum update -y' (tous les paquets à la dernière version)
sys_upgrade_role_full_upgrade_redhat: true

# Sur Suse :
# - si true -> 'zypper update -y'
sys_upgrade_role_full_upgrade_suse: true

# Redémarrer automatiquement si nécessaire ?
# (Sur Debian/Ubuntu : check le fichier /var/run/reboot-required)
sys_upgrade_role_auto_reboot: false

# Delai avant reboot (secondes)
sys_upgrade_role_reboot_timeout: 600

# Message de reboot
sys_upgrade_role_reboot_msg: "Reboot triggered by sys_upgrade_role after system upgrade."

# Liste optionnelle de paquets à exclure des mises à jour (apt/yum/dnf/zypper)
# ATTENTION : la gestion des exclusions est différente selon les OS/modules.
sys_upgrade_role_exclude_packages: []